name: main

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NODE_VERSION: "18.x"
  AZURE_WEBAPP_NAME: "swna-june-development"
  STORYBOOK_WEBAPP_NAME: "swna-june-storybook-development"

jobs:
  application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore Dependencies
        run: npm ci

      - name: Lint Application
        run: npm run lint

      - name: Create Coverage Folder
        run: mkdir coverage

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Build Application
        run: npm run build

  storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore Dependencies
        run: npm ci

      - name: Lint Application
        run: npm run lint

      - name: Create Coverage Folder
        run: mkdir coverage

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Build Storybook
        run: npm run build-storybook

  deploy:
    runs-on: ubuntu-latest
    environment: development
    needs: [application, storybook]

    strategy:
      matrix:
        app_type: [application, storybook]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        if: ${{ matrix.app_type == 'application' }}
      - name: Deploy Application
        uses: azure/webapps-deploy@v2
        with:
          images: ""
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.JUNE_WEB_APP_PUBLISH_PROFILE }}
          package: "./dist"

        if: ${{ matrix.app_type == 'storybook' }}
      - name: Deploy Storybook
        uses: azure/webapps-deploy@v2
        with:
          images: ""
          app-name: ${{ env.STORYBOOK_WEBAPP_NAME }}
          publish-profile: ${{ secrets.JUNE_STORYBOOK_PUBLISH_PROFILE }}
          package: "./storybook-static"
